Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 1908, in <module>
    os.mkdir(directory + "/data/reconstruction_examples/" + identifier)
FileNotFoundError: [Errno 2] No such file or directory: '/home/minseokhwan/xray_projects/multilayer_scintillator/data/reconstruction_examples/ZnSe_Gadox_NaI_67keV_200um'
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd-node1: error: *** STEP 614624.0 ON node1 CANCELLED AT 2025-01-24T13:38:01 ***
slurmstepd-node1: error: *** JOB 614624 ON node1 CANCELLED AT 2025-01-24T13:38:01 ***
