/var/spool/slurmd/job611089/slurm_script: line 10: /home/minseokhwan/xray_projects/geant4/geant4-v11.1.2-install/share/Geant4/geant4make/geant4make.sh: No such file or directory
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
Traceback (most recent call last):
  File "/home/minseokhwan/xray_projects/multilayer_scintillator/run_phantom_geant4.py", line 27, in <module>
    import util.read_txt as txt
ModuleNotFoundError: No module named 'util'
